// Get JOB
export const API_GET_JOB_REQUEST = 'API_GET_JOB_REQUEST';
export const API_GET_JOB_SUCCESS = 'API_GET_JOB_SUCCESS';
export const API_GET_JOB_FAILED = 'API_GET_JOB_FAILED';

// Get JOB BY ID
export const API_GET_JOB_BYID_REQUEST = 'API_GET_JOB_BYID_REQUEST';
export const API_GET_JOB_BYID_SUCCESS = 'API_GET_JOB_BYID_SUCCESS';
export const API_GET_JOB_BYID_FAILED = 'API_GET_JOB_BYID_FAILED';

// APPLIED FOR JOB
export const API_GET_APPLIED_JOB_REQUEST = 'API_GET_APPLIED_JOB_REQUEST';
export const API_GET_APPLIED_JOB_SUCCESS = 'API_GET_APPLIED_JOB_SUCCESS';
export const API_GET_APPLIED_JOB_FAILED = 'API_GET_APPLIED_JOB_FAILED';

// APPLIED FOR JOB
export const API_POST_APPLIED_JOB_REQUEST = 'API_POST_APPLIED_JOB_REQUEST';
export const API_POST_APPLIED_JOB_SUCCESS = 'API_POST_APPLIED_JOB_SUCCESS';
export const API_POST_APPLIED_JOB_FAILED = 'API_POST_APPLIED_JOB_FAILED';

// CREATE JOB
export const API_CREATE_JOB_REQUEST = 'API_CREATE_JOB_REQUEST';
export const API_CREATE_JOB_SUCCESS = 'API_CREATE_JOB_SUCCESS';
export const API_CREATE_JOB_FAILED = 'API_CREATE_JOB_FAILED';

// APPROVED JOB
export const API_APPROVED_JOB_REQUEST = 'API_APPROVED_JOB_REQUEST';
export const API_APPROVED_JOB_SUCCESS = 'API_APPROVED_JOB_SUCCESS';
export const API_APPROVED_JOB_FAILED = 'API_APPROVED_JOB_FAILED';
