// Signup
export const API_SIGNUP_REQUEST = 'API_SIGNUP_REQUEST';
export const API_SIGNUP_SUCCESS = 'API_SIGNUP_SUCCESS';
export const API_SIGNUP_FAILED = 'API_SIGNUP_FAILED';

// Login
export const API_LOGIN_REQUEST = 'API_LOGIN_REQUEST';
export const API_LOGIN_SUCCESS = 'API_LOGIN_SUCCESS';
export const API_LOGIN_FAILED = 'API_LOGIN_FAILED';

// Logout
export const CLEAR_TOKEN = 'CLEAR_TOKEN';

//TOAST TIMEOUT
export const CLEAR_TOAST_TIMEOUT = 'CLEAR_TOAST_TIMEOUT';

// REQUEST PASSWORD RESET CONFIRM
export const API_PASSWORD_RESET_CONFIRM_REQUEST =
  'API_PASSWORD_RESET_CONFIRM_REQUEST';
export const API_PASSWORD_RESET_CONFIRM_SUCCESS =
  'API_PASSWORD_RESET_CONFIRM_SUCCESS';
export const API_PASSWORD_RESET_CONFIRM_FAILED =
  'API_PASSWORD_RESET_CONFIRM_FAILED';

// REQUEST PASSWORD RESET
export const API_PASSWORD_RESET_REQUEST = 'API_PASSWORD_RESET_REQUEST';
export const API_PASSWORD_RESET_SUCCESS = 'API_PASSWORD_RESET_SUCCESS';
export const API_PASSWORD_RESET_FAILED = 'API_PASSWORD_RESET_FAILED';

// REQUEST PASSWORD
export const API_PASSWORD_REQUEST = 'API_PASSWORD_REQUEST';
export const API_PASSWORD_SUCCESS = 'API_PASSWORD_SUCCESS';
export const API_PASSWORD_FAILED = 'API_PASSWORD_FAILED';

// Patch Profile
export const API_PATCH_PROFILE_REQUEST = 'API_PATCH_PROFILE_REQUEST';
export const API_PATCH_PROFILE_SUCCESS = 'API_PATCH_PROFILE_SUCCESS';
export const API_PATCH_PROFILE_FAILED = 'API_PATCH_PROFILE_FAILED';

// Get Profile
export const API_GET_PROFILE_REQUEST = 'API_GET_PROFILE_REQUEST';
export const API_GET_PROFILE_SUCCESS = 'API_GET_PROFILE_SUCCESS';
export const API_GET_PROFILE_FAILED = 'API_GET_PROFILE_FAILED';

// Images Profile
export const API_IMAGES_PROFILE_REQUEST = 'API_IMAGES_PROFILE_REQUEST';
export const API_IMAGES_PROFILE_SUCCESS = 'API_IMAGES_PROFILE_SUCCESS';
export const API_IMAGES_PROFILE_FAILED = 'API_IMAGES_PROFILE_FAILED';

// FEED BACK
export const API_FEED_BACK_REQUEST = 'API_FEED_BACK_REQUEST';
export const API_FEED_BACK_SUCCESS = 'API_FEED_BACK_SUCCESS';
export const API_FEED_BACK_FAILED = 'API_FEED_BACK_FAILED';

// Verify Token
export const API_Verify_TOKEN_REQUEST = 'API_Verify_TOKEN_REQUEST';
export const API_Verify_TOKEN_SUCCESS = 'API_Verify_TOKEN_SUCCESS';
export const API_Verify_TOKEN_FAILED = 'API_Verify_TOKEN_FAILED';
