// GET ALL USER CHAT
export const API_GET_ALL_USER_CHAT_REQUEST = 'API_GET_ALL_USER_CHAT_REQUEST';
export const API_GET_ALL_USER_CHAT_SUCCESS = 'API_GET_ALL_USER_CHAT_SUCCESS';
export const API_GET_ALL_USER_CHAT_FAILED = 'API_GET_ALL_USER_CHAT_FAILED';
