// GET ALL USERS
export const API_GET_ALL_USERS_REQUEST = 'API_GET_ALL_USERS_REQUEST';
export const API_GET_ALL_USERS_SUCCESS = 'API_GET_ALL_USERS_SUCCESS';
export const API_GET_ALL_USERS_FAILED = 'API_GET_ALL_USERS_FAILED';

// Get All Users With User ID
export const API_GET_USER_ID_REQUEST = 'API_GET_USER_ID_REQUEST';
export const API_GET_USER_ID_SUCCESS = 'API_GET_USER_ID_SUCCESS';
export const API_GET_USER_ID_FAILED = 'API_GET_USER_ID_FAILED';

// GET ALL Followers login USER
export const API_GET_ALL_USERS_FOLLOWER_REQUEST =
  'API_GET_ALL_USERS_FOLLOWER_REQUEST';
export const API_GET_ALL_USERS_FOLLOWER_SUCCESS =
  'API_GET_ALL_USERS_FOLLOWER_SUCCESS';
export const API_GET_ALL_USERS_FOLLOWER_FAILED =
  'API_GET_ALL_USERS_FOLLOWER_FAILED';

// GET ALL Following USER
export const API_GET_ALL_FOLLOWING_REQUEST = 'API_GET_ALL_FOLLOWING_REQUEST';
export const API_GET_ALL_FOLLOWING_SUCCESS = 'API_GET_ALL_FOLLOWING_SUCCESS';
export const API_GET_ALL_FOLLOWING_FAILED = 'API_GET_ALL_FOLLOWING_FAILED';

// GET ALL Followers With USER ID
export const API_GET_ALL_FOLLOWERS_REQUEST = 'API_GET_ALL_FOLLOWERS_REQUEST';
export const API_GET_ALL_FOLLOWERS_SUCCESS = 'API_GET_ALL_FOLLOWERS_SUCCESS';
export const API_GET_ALL_FOLLOWERS_FAILED = 'API_GET_ALL_FOLLOWERS_FAILED';

// Follow
export const API_POST_FOLLOW_REQUEST = 'API_POST_FOLLOW_REQUEST';
export const API_POST_FOLLOW_SUCCESS = 'API_POST_FOLLOW_SUCCESS';
export const API_POST_FOLLOW_FAILED = 'API_POST_FOLLOW_FAILED';

//DELETE Follow
export const API_DELETE_FOLLOW_REQUEST = 'API_DELETE_FOLLOW_REQUEST';
export const API_DELETE_FOLLOW_SUCCESS = 'API_DELETE_FOLLOW_SUCCESS';
export const API_DELETE_FOLLOW_FAILED = 'API_DELETE_FOLLOW_FAILED';

//GET Block User
export const API_GET_BLOCK_USER_REQUEST = 'API_GET_BLOCK_USER_REQUEST';
export const API_GET_BLOCK_USER_SUCCESS = 'API_GET_BLOCK_USER_SUCCESS';
export const API_GET_BLOCK_USER_FAILED = 'API_GET_BLOCK_USER_FAILED';

//Delete Block User
export const API_DELETE_BLOCK_USER_REQUEST = 'API_DELETE_BLOCK_USER_REQUEST';
export const API_DELETE_BLOCK_USER_SUCCESS = 'API_DELETE_BLOCK_USER_SUCCESS';
export const API_DELETE_BLOCK_USER_FAILED = 'API_DELETE_BLOCK_USER_FAILED';

// Block User POst
export const API_BLOCK_USER_REQUEST = 'API_BLOCK_USER_REQUEST';
export const API_BLOCK_USER_SUCCESS = 'API_BLOCK_USER_SUCCESS';
export const API_BLOCK_USER_FAILED = 'API_BLOCK_USER_FAILED';
