// Portfilo
export const API_PORTFILO_REQUEST = 'API_PORTFILO_REQUEST';
export const API_PORTFILO_SUCCESS = 'API_PORTFILO_SUCCESS';
export const API_PORTFILO_FAILED = 'API_PORTFILO_FAILED';

//Get Portfilo
export const API_GET_PORTFILO_REQUEST = 'API_GET_PORTFILO_REQUEST';
export const API_GET_PORTFILO_SUCCESS = 'API_GET_PORTFILO_SUCCESS';
export const API_GET_PORTFILO_FAILED = 'API_GET_PORTFILO_FAILED';

//PATCH Portfilo
export const API_PATCH_PORTFILO_REQUEST = 'API_PATCH_PORTFILO_REQUEST';
export const API_PATCH_PORTFILO_SUCCESS = 'API_PATCH_PORTFILO_SUCCESS';
export const API_PATCH_PORTFILO_FAILED = 'API_PATCH_PORTFILO_FAILED';

//Like Portfilo
export const API_LIKE_PORTFILO_REQUEST = 'API_LIKE_PORTFILO_REQUEST';
export const API_LIKE_PORTFILO_SUCCESS = 'API_LIKE_PORTFILO_SUCCESS';
export const API_LIKE_PORTFILO_FAILED = 'API_LIKE_PORTFILO_FAILED';

//Delete Like Portfilo
export const API_DELETE_LIKE_PORTFILO_REQUEST =
  'API_DELETE_LIKE_PORTFILO_REQUEST';
export const API_DELETE_LIKE_PORTFILO_SUCCESS =
  'API_DELETE_LIKE_PORTFILO_SUCCESS';
export const API_DELETE_LIKE_PORTFILO_FAILED =
  'API_DELETE_LIKE_PORTFILO_FAILED';

//rating Portfilo
export const API_RATING_PORTFILO_REQUEST = 'API_RATING_PORTFILO_REQUEST';
export const API_RATING_PORTFILO_SUCCESS = 'API_RATING_PORTFILO_SUCCESS';
export const API_RATING_PORTFILO_FAILED = 'API_RATING_PORTFILO_FAILED';
