// Get Posts
export const API_GET_POSTS_REQUEST = 'API_GET_POSTS_REQUEST';
export const API_GET_POSTS_SUCCESS = 'API_GET_POSTS_SUCCESS';
export const API_GET_POSTS_FAILED = 'API_GET_POSTS_FAILED';

// Create Post
export const API_POST_CREATE_POST_REQUEST = 'API_POST_CREATE_POST_REQUEST';
export const API_POST_CREATE_POST_SUCCESS = 'API_POST_CREATE_POST_SUCCESS';
export const API_POST_CREATE_POST_FAIL = 'API_POST_CREATE_POST_FAIL';

// Delte Post
export const API_DELETE_POST_REQUEST = 'API_DELETE_POST_REQUEST';
export const API_DELETE_POST_SUCCESS = 'API_DELETE_POST_SUCCESS';
export const API_DELETE_POST_FAIL = 'API_DELETE_POST_FAIL';

// Post Images
export const API_POST_IMAGES_REQUEST = 'API_POST_IMAGES_REQUEST';
export const API_POST_IMAGES_SUCCESS = 'API_POST_IMAGES_SUCCESS';
export const API_POST_IMAGES_FAIL = 'API_POST_IMAGES_FAIL';

// ----------Post Likes ----------
// handle like
export const OPEN_LIKE_REACTION_BAR = 'OPEN_LIKE_REACTION_BAR';

// Get
export const API_GET_POST_LIKES_REQUEST = 'API_GET_POST_LIKES_REQUEST';
export const API_GET_POST_LIKES_SUCCESS = 'API_GET_POST_LIKES_SUCCESS';
export const API_GET_POST_LIKES_FAILED = 'API_GET_POST_LIKES_FAILED';

// Post
export const API_POST_LIKE_POST_REQUEST = 'API_POST_LIKE_POST_REQUEST';
export const API_POST_LIKE_POST_SUCCESS = 'API_POST_LIKE_POST_SUCCESS';
export const API_POST_LIKE_POST_FAILED = 'API_POST_LIKE_POST_FAILED';

// USER GET POST
export const API_GET_POST_USER_REQUEST = 'API_GET_POST_USER_REQUEST';
export const API_GET_POST_USER_SUCCESS = 'API_GET_POST_USER_SUCCESS';
export const API_GET_POST_USER_FAILED = 'API_GET_POST_USER_FAILED';

// Follower USER GET POST
export const API_GET_FOLLOWER_USER_POST_USER_REQUEST =
  'API_GET_FOLLOWER_USER_POST_USER_REQUEST';
export const API_GET_FOLLOWER_USER_POST_USER_SUCCESS =
  'API_GET_FOLLOWER_USER_POST_USER_SUCCESS';
export const API_GET_FOLLOWER_USER_POST_USER_FAILED =
  'API_GET_FOLLOWER_USER_POST_USER_FAILED';

// Block User
export const API_BLOCK_USER_REQUEST = 'API_BLOCK_USER_REQUEST';
export const API_BLOCK_USER_SUCCESS = 'API_BLOCK_USER_SUCCESS';
export const API_BLOCK_USER_FAILED = 'API_BLOCK_USER_FAILED';

//GET Block User
export const API_GET_BLOCK_USER_REQUEST = 'API_GET_BLOCK_USER_REQUEST';
export const API_GET_BLOCK_USER_SUCCESS = 'API_GET_BLOCK_USER_SUCCESS';
export const API_GET_BLOCK_USER_FAILED = 'API_GET_BLOCK_USER_FAILED';

//Delete Block User
export const API_DELETE_BLOCK_USER_REQUEST = 'API_DELETE_BLOCK_USER_REQUEST';
export const API_DELETE_BLOCK_USER_SUCCESS = 'API_DELETE_BLOCK_USER_SUCCESS';
export const API_DELETE_BLOCK_USER_FAILED = 'API_DELETE_BLOCK_USER_FAILED';

// DISLIKE Post
export const API_DELETE_LIKE_POST_REQUEST = 'API_DELETE_LIKE_POST_REQUEST';
export const API_DELETE_LIKE_POST_SUCCESS = 'API_DELETE_LIKE_POST_SUCCESS';
export const API_DELETE_LIKE_POST_FAILED = 'API_DELETE_LIKE_POST_FAILED';

// ---------- Comments ----------
// GET
export const API_GET_COMMENTS_POST_REQUEST = 'API_GET_COMMENTS_POST_REQUEST';
export const API_GET_COMMENTS_POST_SUCCESS = 'API_GET_COMMENTS_POST_SUCCESS';
export const API_GET_COMMENTS_POST_FAILED = 'API_GET_COMMENTS_POST_FAILED';

// POST
export const API_POST_COMMENTS_POST_REQUEST = 'API_POST_COMMENTS_POST_REQUEST';
export const API_POST_COMMENTS_POST_SUCCESS = 'API_POST_COMMENTS_POST_SUCCESS';
export const API_POST_COMMENTS_POST_FAILED = 'API_POST_COMMENTS_POST_FAILED';
