// Get User Search Result
export const API_GET_USER_SEARCH_REQUEST = "API_GET_USER_SEARCH_REQUEST"
export const API_GET_USER_SEARCH_SUCCESS = "API_GET_USER_SEARCH_SUCCESS"
export const API_GET_USER_SEARCH_FAILED = "API_GET_USER_SEARCH_FAILED"


export const CLEAR_SEARCH_RESULT = "CLEAR_SEARCH_RESULT"