let Athletes = [
  {
    name: 'guilemrose',
    id: 1,
    pic: require('../../assets/Athletes1.jpg'),
    discription: 'RealityTvStar-Chris',
    rs: `Rs 22,100.00 +`,
    hour: '24 hr',
  },
  {
    name: 'john',
    id: 2,
    pic: require('../../assets/Athletes2.jpg'),
    discription: 'RealityTvStar-Singer',
    rs: `Rs 22,100.00 +`,
    hour: '24 hr',
  },
  {
    name: 'carly',
    id: 3,
    pic: require('../../assets/Athletes3.jpg'),
    discription: 'RealityTvStar-Entertenmant',
    rs: `Rs 22,100.00 +`,
    hour: '24 hr',
  },
  {
    name: 'tom',
    id: 4,
    pic: require('../../assets/Athletes4.jpg'),
    discription: 'RealityTvStar-Comedy',
    rs: `Rs 22,100.00 +`,
    hour: '24 hr',
  },
  {
    name: 'tom',
    id: 5,
    pic: require('../../assets/Athletes5.jpg'),
    discription: 'RealityTvStar-Smart',
    rs: `Rs 22,100.00 +`,
    hour: '24 hr',
  },
  {
    name: 'tom',
    id: 6,
    pic: require('../../assets/Athletes6.jpg'),
    discription: 'RealityTvStar-Funny',
    rs: `Rs 22,100.00 +`,
    hour: '24 hr',
  },
  {
    name: 'tom',
    id: 7,
    pic: require('../../assets/Athletes7.jpg'),
    discription: 'RealityTvStar-Cool',
    rs: `Rs 22,100.00 +`,
    hour: '24 hr',
  },
];
export default Athletes;
