let CreatorsData = [
  {
    name: 'guilemrose',
    id: 1,
    pic: require('../../assets/people8.jpg'),
    discription: 'RealityTvStar-Chris',
    rs: `Rs 22,100.00 +`,
    hour: '24 hr',
  },
  {
    name: 'john',
    id: 2,
    pic: require('../../assets/people9.jpg'),
    discription: 'RealityTvStar-Singer',
    rs: `Rs 22,100.00 +`,
    hour: '24 hr',
  },
  {
    name: 'carly',
    id: 3,
    pic: require('../../assets/people10.jpg'),
    discription: 'RealityTvStar-Entertenmant',
    rs: `Rs 22,100.00 +`,
    hour: '24 hr',
  },
  {
    name: 'tom',
    id: 4,
    pic: require('../../assets/people11.jpg'),
    discription: 'RealityTvStar-Comedy',
    rs: `Rs 22,100.00 +`,
    hour: '24 hr',
  },
  {
    name: 'tom',
    id: 5,
    pic: require('../../assets/people2.jpg'),
    discription: 'RealityTvStar-Smart',
    rs: `Rs 22,100.00 +`,
    hour: '24 hr',
  },
  {
    name: 'tom',
    id: 6,
    pic: require('../../assets/people12.jpg'),
    discription: 'RealityTvStar-Funny',
    rs: `Rs 22,100.00 +`,
    hour: '24 hr',
  },
  {
    name: 'tom',
    id: 7,
    pic: require('../../assets/people13.jpg'),
    discription: 'RealityTvStar-Cool',
    rs: `Rs 22,100.00 +`,
    hour: '24 hr',
  },
];
export default CreatorsData;
