import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import {Colors} from './../../constants/Colors';

const styles = StyleSheet.create({
  backgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  contentContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    width: 200,
    height: 200,
    resizeMode: 'contain',
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: 'white',
    marginTop: 32,
    marginBottom: 16,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 18,
    color: 'white',
    textAlign: 'center',
    marginHorizontal: 64,
    marginBottom: 32,
  },
  buttonContainer: {
    position: 'absolute',
    bottom: 64,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    backgroundColor: 'white',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 32,
  },
  buttonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'black',
    textAlign: 'center',
  },
  inputView: {
    borderWidth: 1,
    marginBottom: 20,
    borderStyle: 'solid',
    borderColor: Colors.grayColor,
    borderRadius: 20,
  },
  inputHead: {
    color: Colors.black,
    fontSize: 13,
    fontWeight: '700',
    paddingHorizontal: 12,
  },
  input: {
    height: 50,
    color: Colors.black,
    fontSize: 14,
    paddingHorizontal: 9,
    borderRadius: 20,
  },
  passView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // width:'50%'
  },
  checkbox: {
    alignSelf: 'center',
  },
  terms: {
    color: Colors.blackColor,
    fontSize: 15,
  },
  colorTerms: {
    color: Colors.blueThemeColor,
  },
  btnSubmit: {
    display: 'flex',
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    width: '95%',
    height: 50,
    borderRadius: 22,
    marginTop: 22,
  },
  SignupbtnSubmit: {
    display: 'flex',
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    width: '90%',
    height: 50,
    borderRadius: 8,
    marginTop: 22,
    marginBottom: 20,
  },
  txtSubmit: {
    color: Colors.whiteColor,
    fontSize: 15,
  },
  lineView: {
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: 20,
    flexDirection: 'row',
    paddingHorizontal: 10,
  },
  line: {
    flex: 1,
    // marginHorizontal: 3,
    borderBottomWidth: 2,
    borderColor: Colors.grayColor,
    borderStyle: 'solid',
    // paddingHorizontal: 10,
    paddingHorizontal: 10,
  },
  inputHead: {
    color: Colors.black,
    fontSize: 13,
    marginBottom: 5,
    paddingHorizontal: 12,
  },
  Googleimage: {
    width: 39,
    height: 34,
    marginRight: 5,
    borderRadius: 25,
  },
  mainbtnview: {
    display: 'flex',
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    width: '100%',
    flexDirection: 'row',
    marginTop: 50,
  },
  btnview: {
    display: 'flex',
    flexDirection: 'row',
    // fontSize: 24,
    textAlign: 'center',
    fontWeight: 'bold',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnTxt: {
    display: 'flex',
    color: Colors.blackColor,
    fontSize: 15,
    fontWeight: '700',
  },
  Messagespic: {
    width: 60,
    height: 57,
    alignSelf: 'center',
  },
  MessageText: {
    display: 'flex',
    alignSelf: 'center',
    marginTop: 20,
    marginBottom: 29,
    fontSize: 20,
  },
  NamesFieldView: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-around',
  },
  label: {
    fontWeight: 'bold',
  },
  dropdownContainer: {
    height: 40,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    backgroundColor: '#fff',
  },
  dropdown: {
    backgroundColor: '#fff',
    borderRadius: 5,
  },
  dropdownItem: {
    justifyContent: 'flex-start',
  },
  dropdownMenu: {
    marginTop: 10,
    borderRadius: 5,
    backgroundColor: '#fff',
  },
  container: {
    // flex: 1,
    // width:"100%",
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    // marginRight:55
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    borderBottomWidth: 1,
    borderBottomColor: Colors.grayColor,
    padding: 10,
    width: '100%',
  },
  selectedCountry: {
    fontSize: 16,
    // paddingRight: 10,
  },
  countryCode: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  countryPickerButton: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
    alignContent: 'flex-start',
    alignItems: 'flex-start',
  },
  closeButtonImage: {
    resizeMode: 'contain',
    width: 20,
    height: 20,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 50,
    backgroundColor: Colors.whiteColor,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopWidth: 1,
    borderTopColor: Colors.grayColor,
    flexDirection: 'row',
    paddingHorizontal: 12,
  },
  text: {
    fontSize: 16,
    color: Colors.grayColor,
  },
  button: {
    fontSize: 16,
    color: Colors.blueThemeColor,
    marginLeft: 10,
  },

  Trackcontainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    padding: 5,
    marginHorizontal: 12,
  },
  Trackinput: {
    flex: 1,
    height: 40,
    paddingHorizontal: 10,
  },
  tracktransfer: {
    display: 'flex',
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    width: '45%',
    height: 50,
    borderRadius: 8,
    marginTop: 22,
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: Colors.grayColor,
    flexDirection: 'row',
    borderRadius: 15,
  },

  bankView: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    marginHorizontal: 10,
  },

  bankIconView: {
    flexDirection: 'column',
    borderRadius: 10,
    borderWidth: 1,
    width: '20%',
    alignItems: 'center',
    paddingBottom: 10,
    marginHorizontal: 7,
    paddingTop: 10,
    marginTop: 10,
  },
  subDiv: {
    display: 'flex',
    flexDirection: 'column',
    height: '80%',
    justifyContent: 'space-between',
  },
  modal: {
    width: '95%',
    height: '50%',
    backgroundColor: Colors.whiteThemeColor,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    alignSelf: 'center',
    position: 'absolute',
    bottom: 0,
  },

  //   radio button
  radioButtonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 45,
    padding: 9,
  },
  radioButton: {
    height: 20,
    width: 20,
    backgroundColor: '#F8F8F8',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E6E6E6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonIcon: {
    height: 14,
    width: 14,
    borderRadius: 7,
    backgroundColor: '#98CFB6',
  },
  radioButtonText: {
    fontSize: 16,
    marginLeft: 16,
  },

  // birthday text

  inputWidth: {
    display: 'flex',
    flexDirection: 'row',
    width: 300,
    height: 50,
    borderColor: Colors.grayColor,
    borderBottomWidth: 1,
    marginVertical: 13,
  },

  dateText: {
    alignSelf: 'center',
    paddingHorizontal: 20,
  },
});

export default styles;
